### ISSUE TITLE
Использовать инструменты ASP для хендла ошибок

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#10]
Во всех методах есть `catch(Exception e)`. Средствами ASP можно реализовать единый обработик таких ошибок.

**Comment by hrrrrustic** [comment]
Добавил middleware для обработки ошибок, в нем просто отправляю ex.Message в теле ответа(в прицнипе абсолютно тоже самое, что и было в кетчах). Потом может быть буду отправлять больше информации, это легко добавить.  + Немного изменил экстеншн для экспешна, ну и удалил все кетчи
Коммит : https://github.com/hrrrrustic/BirdyAPI/commit/52047415fa03d1ff535f644e36d27197b6a8c98f
