### ISSUE TITLE
Реализовать адекватную авторизацию используя встроенные инструменты ASP

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#2]
Асп предоставляет много функционала с коробки на который можно завязаться, чтобы не писать свои костыли с проверкой на авторизацию, аутентификацию

**Comment by hrrrrustic** [comment]
Изобретаем велосипеды

**Comment by FrediKats** [comment]
Отлично объяснил закрытие ишуи!
