### ISSUE TITLE
Не корректный ключ для таблицы Friends

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#5]
Для таблицы Friend обавлен ключ на одно из поле. Это значит, что поле должно быть уникальным, а значит нельзя вставить записи о том, что у человека >1 друга. Нужно посмотреть и почитать о составных ключах и заюзать их

https://github.com/birdy-messenger/BirdyAPI/blob/master/BirdyAPI/DataBaseModels/Friends.cs#L12-L14

```
[Key]
public int FirstUserID { get; set; }
public int SecondUserID { get; set; }
```

**Comment by hrrrrustic** [comment]
fixed
