### ISSUE TITLE
Вынести из сервисов логику создания объектов

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#6]
Есть ряд  методов, где с одного объекта создается другой. Например `RegistrationDto => User`. Стоит вынести такую логику в статик методы классов (в данном случае `User`). В итоге получишь метод `static User Create(RegistrationDto dto)`. Таки образом, у тебя логику создания сущности будет в классе, которые описывает сущность.

**Comment by hrrrrustic** [comment]
Сделал методы Create при наличии хоть каких-то параметров НЕ зависящих от пользователя(например Guid.NewGuid), из Create тыкаю private конструктор. Добавил везде пустой базовый коснтруктор.
Коммит : https://github.com/hrrrrustic/BirdyAPI/commit/ece7f8c79d38cb3a4c619a9a948a77e6e6f6b54b
