### ISSUE TITLE
Добавить сообщения к ошибкам

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#7]
Во многих местах бросается какой-то эксепшен без описания. Например:

https://github.com/birdy-messenger/BirdyAPI/blob/64fa43bf474cd07ff10db8112cb27cb92374ba3d/BirdyAPI/Services/AppEntryService.cs#L114-L122

Чтобы сделать более юзер-френдли систему, стоит добавить описание ошибок. В данном кейсе - что ошибка появилась потому что пароль такой же, а не потому что ввели неправильно.

**Comment by hrrrrustic** [comment]
Добавил везде ex.Message при бросании эксепшна
Коммит 
 : https://github.com/hrrrrustic/BirdyAPI/commit/80c5bdd939c1fd49773de0a706d7e11e3a8d7fb9
