### ISSUE TITLE
feat: Добавить аргументы в запрос списков чатов

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#8]
В коде захардкодил кол-во чатов, которые возвращаются - это не гуд.

https://github.com/birdy-messenger/BirdyAPI/blob/61d1a413883fa9c50605f70b548a8d801b74a6b5/BirdyAPI/Services/DialogService.cs#L53-L54

Стоит реализовать два дополнительных параметра - offset и count. Посмотреть пример можно вк. И сделать это не обязательными параметрами (int?).

**Comment by hrrrrustic** [comment]
Добавил в GET запрос конкретного чата и диалога параметры, сделал .Skip(offset).Take(count)
Дефолтное значение offset - 0, count - 50
Коммит : https://github.com/hrrrrustic/BirdyAPI/commit/589b7ed916bc81bb4ca1bf0c970387ecfeae8f99
