### ISSUE TITLE
Некорректные названия полей метода GetChat

### ISSUE THREAD

**Issue by FrediKats** [birdy-messenger/BirdyAPI#9]
В сервисе ChatService  метод GetChat возвращает Tuple, в итоге получаем 
```
{
      "item1": "string",
      "item2": 1
}
```

Нужно  исправить, чтобы возвращаемый тип был адекватен. Использовать либо имена из ValueTuple, либо сделать класс для этого.

**Comment by hrrrrustic** [comment]
Добавил dto со статусом и тегом, теперь нормально отображает. Имена с ValueTuple не работают. Не сериализуются и все, все равно остается item1 и item2
Коммит : https://github.com/hrrrrustic/BirdyAPI/commit/87f403f6f5c38ce45ae65f41f367ad7fe8021511

**Comment by FrediKats** [comment]
А еще есь анонимные типы!
